server:
  port: 8282

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8181/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}

zuul:
  routes:
    services1:
      path: /service1/**
      serviceId: service1
      stripPrefix: false
    services2:
      path: /service2/**
      serviceId: service2
      stripPrefix: false